development:
  adapter: postgresql
  encoding: unicode
  database: learnplatform
  pool: 5
  username: learnplatform
  password: 1ZGdRtY0mC
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: learnplatform_test
  pool: 5
  username: learnplatform
  password: 1ZGdRtY0mC
  host: localhost
  min_messages: warning
